using System.Collections.Generic;

namespace MmorpgPrototype
{
    // Tabla espanola por defecto. Fuente unica para el generador de assets
    // (MMORPG > Localization > Generate Localization) y el fallback runtime.
    public static class DefaultLocalization
    {
        public static Dictionary<string, string> CreateSpanish()
        {
            return new Dictionary<string, string>
            {
                // Progresion
                { "status.level_up", "Subiste a nivel {0}." },
                { "status.max_level", "Alcanzaste el nivel maximo {0}." },
                { "status.class_active", "Clase activa: {0}" },
                { "rebirth.required", "Necesitas alcanzar el nivel {0} para Renacer." },
                { "rebirth.success", "Renacimiento {0}: vuelves al nivel 1 y ganas Renombre {1}." },
                { "rebirth.renown", "Renombre {0}: +{1:0}% EXP permanente" },
                { "hud.rebirth", "  Renacer {0} | Renombre {1}" },
                { "feed.attribute_points", "+{0} puntos de atributo" },
                { "net.level_up", "subio a nivel {0}" },
                { "net.status_offline", "Offline" },
                { "net.status_connecting", "Conectando..." },
                { "net.status_online", "Online: {0}" },
                { "net.status_no_connection", "Sin conexion: {0}" },
                { "net.status_server_disconnected", "Servidor desconectado." },
                { "net.status_connection_closed", "Conexion cerrada: {0}" },
                { "net.status_offline_hint", "Offline: inicia el server y presiona ONLINE." },
                { "net.status_send_failed", "Envio fallido: {0}" },
                { "net.chat_system", "Sistema" },
                { "net.chat_valley", "Valle" },
                { "net.chat_server", "Servidor" },
                { "net.connected", "Conectado al servidor local." },
                { "net.chat_placeholder", "mensaje..." },
                { "net.url_placeholder", "server url" },
                { "net.server_name", "S-01  •  Valle de las Reliquias" },
                { "net.server_settings", "Servidor y conexion" },
                { "net.connection_details", "Direccion y diagnostico" },
                { "net.connection_hint", "La conexion completa solo aparece aqui." },
                { "net.disconnected_short", "DESCONECTADO" },
                { "net.connecting_short", "CONECTANDO" },
                { "net.connected_short", "CONECTADO" },
                { "net.error_short", "ERROR" },
                { "attr.no_points", "No tienes puntos de atributo disponibles." },
                { "attr.strength_up", "Fuerza {0} (+{1} dano)" },
                { "attr.vitality_up", "Vitalidad {0} (+{1} vida)" },
                { "attr.agility_up", "Agilidad {0} (velocidad y critico)" },

                // Mejora de equipo
                { "upgrade.need_weapon", "Equipa un arma primero (boton EQUIPAR)." },
                { "upgrade.need_armor", "Equipa una pieza de armadura primero (boton EQUIPAR)." },
                { "upgrade.not_ready", "Sistema de mejora no inicializado." },
                { "upgrade.at_max", "{0} ya esta al maximo (+{1})." },
                { "upgrade.need_gold", "Oro insuficiente: necesitas {0}." },
                { "upgrade.need_material", "Necesitas {0} {1}." },
                { "upgrade.rune_used", "Runa de proteccion aplicada" },
                { "upgrade.success", "{0} mejorado a +{1}." },
                { "upgrade.feed_success", "{0} +{1}" },
                { "upgrade.fail_protected", "La mejora fallo, pero la runa protegio {0}." },
                { "upgrade.fail_kept", "La mejora de {0} fallo. El objeto se mantiene." },
                { "upgrade.fail_down", "La mejora fallo: {0} bajo a +{1}." },
                { "upgrade.feed_down", "{0} bajo a +{1}" },
                { "upgrade.destroyed", "La mejora fallo: {0} se destruyo." },
                { "upgrade.feed_destroyed", "{0} destruido en la mejora" },
                { "net.upgrade", "mejoro {0} a +{1}" },
                { "net.rejected", "Accion '{0}' rechazada por el servidor ({1})." },

                // Pociones
                { "potion.none", "No tienes pociones." },
                { "potion.used", "Usaste Pocion menor." },
                { "potion.feed", "Pocion usada: +{0} vida" },

                // Equipamiento
                { "equip.feed", "Equipado: {0}" },
                { "equip.updated", "Equipo actualizado." },
                { "equip.nothing_better", "No hay equipo mejor en el inventario." },
                { "equip.need_level", "Necesitas nivel {0} para {1}." },
                { "equip.wrong_class", "Tu clase no puede usar {0}." },
                { "equip.cannot", "No puedes equipar {0}." },
                { "hud.equipment", "Equipo: {0}" },
                { "hud.no_pieces", "sin piezas" },

                // Inventario
                { "inv.feed_add", "+{0} {1}" },
                { "inv.empty", "Inventario: vacio" },
                { "inv.summary", "Inventario: {0}" },

                // Mascotas
                { "pet.none", "No tienes mascotas." },
                { "pet.locked", "Esa mascota aun no esta desbloqueada." },
                { "pet.summoned", "{0} te acompana (+{1}% EXP, +{2}% oro)." },
                { "pet.feed_summon", "Mascota invocada: {0}" },
                { "pet.dismissed", "{0} descansa." },
                { "pet.feed_dismiss", "Mascota guardada: {0}" },

                // Monturas
                { "mount.none", "No tienes monturas." },
                { "mount.locked", "Esa montura aun no esta desbloqueada." },
                { "mount.need_level", "Necesitas nivel {0} para montar {1}." },
                { "mount.mounted", "Montaste {0} (velocidad x{1})." },
                { "mount.feed", "Montura: {0}" },
                { "mount.dismounted", "Bajaste de {0}." },

                // Almacen
                { "storage.nothing", "No tienes materiales para guardar." },
                { "storage.deposited", "Guardaste {0} materiales en el almacen." },
                { "storage.feed", "Almacen: +{0} materiales" },
                { "storage.withdrawn", "Retiraste todo del almacen." },
                { "storage.too_far", "Acercate al Almacen del campamento." },

                // NPCs
                { "shop.dialog", "Mercader: bienvenido, viajero. Compra pociones o mejora tu equipo." },
                { "shop.too_far", "Acercate al Mercader del Valle." },
                { "shop.need_gold", "Necesitas {0} oro para comprar pocion." },
                { "shop.bought_potion", "Compraste Pocion menor." },
                { "shop.feed_potion", "Mercader: pocion comprada" },
                { "smith.dialog", "Herrero: traeme oro y materiales y reforzare tu equipo." },
                { "smith.too_far", "Acercate al Herrero del campamento." },
                { "world.shop_label", "Mercader\ncompra pociones" },
                { "world.smith_label", "Herrero\nmejora tu equipo" },
                { "world.storage_label", "Almacen\nguarda materiales" },
                { "world.zone_sign", "{0}\nZona {1}-{2}" },

                // Misiones
                { "quest.none", "Mision: -" },
                { "quest.all_done", "Mision: valle estabilizado. Esperando nuevas tareas." },
                { "quest.summary", "Mision: {0} - {1}" },
                { "quest.feed_progress", "Mision: {0} {1}/{2}" },
                { "quest.completed", "Mision completada: {0}. {1}" },
                { "quest.new", "Nueva mision: {0}" },
                { "reward.feed", "{0}: +{1} EXP, +{2} oro" },
                { "contract.summary", "Contratos diarios {0}/{1}" },
                { "contract.progress", "Contrato: {0} {1}/{2}" },
                { "contract.complete", "Contrato completado: {0}." },
                { "contract.normal_title", "Caceria: {0}" },
                { "contract.elite_title", "Caceria elite: {0}" },
                { "contract.material_title", "Forja: {0}" },
                { "contract.ok", "OK {0}" },
                { "contract.pending", "- {0} {1}/{2}" },

                // Combate
                { "combat.no_target", "No hay enemigos en rango." },
                { "combat.already_dead", "El objetivo ya fue derrotado." },
                { "combat.dodged", "{0} esquivo tu ataque." },
                { "combat.defeated", "{0} derrotado." },
                { "combat.crit", "Golpe critico a {0} por {1}." },
                { "combat.hit", "Golpeaste a {0} por {1}." },
                { "combat.miss_popup", "Fallo" },
                { "combat.dodge_popup", "Esquivado" },

                // Habilidades
                { "skill.one_cooldown", "Habilidad 1 en recarga." },
                { "skill.two_cooldown", "Habilidad 2 en recarga." },
                { "skill.cooldown", "{0} en recarga." },
                { "skill.locked_level", "Habilidad bloqueada: requiere nivel {0}." },
                { "skill.locked_label", "{0} {1} Nv{2}" },
                { "skill.upgrade_need_tome", "Necesitas {0} Manual(es) de habilidades." },
                { "skill.upgrade_max", "{0} ya esta en nivel maximo ({1})." },
                { "skill.upgraded", "{0} mejorada a nivel {1}." },
                { "skill.upgrade_feed", "Habilidad mejorada: {0} Nv{1}." },
                { "skill.ultimate_cooldown", "La habilidad final estara lista en {0}." },
                { "skill.ultimate_no_target", "La habilidad final necesita un enemigo cercano." },
                { "skill.ultimate_used", "{0}: fatality ejecutado." },
                { "skill.ultimate_feed", "Habilidad final usada: {0}." },
                { "skill.need_energy", "Necesitas {0} de energia." },
                { "skill.auto_unlocked", "Desbloqueaste {0} al alcanzar nivel {1}." },
                { "skill.cleave_hit", "Corte pesado golpeo {0} enemigo(s)." },
                { "skill.cleave_miss", "Corte pesado no encontro objetivo." },
                { "skill.ninja_dash_hit", "Estocada veloz conecto." },
                { "skill.ninja_dash", "Estocada veloz." },
                { "skill.no_target", "{0}: sin objetivo." },
                { "skill.hit", "{0} impacto a {1}." },
                { "skill.heal", "Bendicion espiritual: curacion." },
                { "skill.mark_no_target", "Marca del vacio: sin objetivo." },
                { "skill.mark_hit", "Marca del vacio debilito a {0}." },
                { "skill.buff", "{0}: dano aumentado." },
                { "skill.spiritual_bolt", "Rayo espiritual" },
                { "skill.dark_blade", "Hoja oscura" },
                { "skill.shadow_dash", "Sombra fugaz" },
                { "skill.battle_cry", "Grito de batalla" },

                // Recompensas de enemigos
                { "reward.kill", "+{0} EXP, +{1} oro" },
                { "reward.kill_loot", "+{0} EXP, +{1} oro, loot: {2}" },
                { "reward.kill_feed", "+{0} EXP  +{1} oro" },

                // Zonas
                { "zone.boss_respawn", "{0} reaparecera pronto" },
                { "zone.elite_label", "Elite" },
                { "zone.boss_label", "Jefe de zona" },
                { "poi.elite", "{0}: santuario de elite listo para explorar." },
                { "poi.boss", "{0}: el landmark del jefe guarda una amenaza mayor." },
                { "poi.entry", "Entrada a {0}. Sigue el camino principal para avanzar." },
                { "poi.safe", "Campamento seguro de {0}: aqui no hay combate." },
                { "poi.safe_combat_blocked", "Estas en una zona segura: aqui no se puede combatir." },
                { "poi.already_explored", "Ya exploraste {0} en esta sesion." },
                { "poi.reward", "Recompensa de exploracion: +{0} EXP, +{1} oro." },
                { "poi.no_target", "No hay un punto de interes cercano." },
                { "poi.too_far", "Acercate a {0} para explorar este punto." },
                { "poi.interacted", "Exploraste: {0}" },
                { "event.monolith_name", "Monolito Corrupto" },
                { "event.monolith_label", "Monolito Corrupto\nEvento de mapa" },
                { "event.monolith_spawned", "Evento: aparecio el Monolito Corrupto al sur." },
                { "event.monolith_completed", "Evento completado: el monolito reaparecera despues." },
                { "event.daily_started", "Evento diario: Caceria de Reliquias activa. Derrota 5 enemigos." },
                { "event.daily_progress", "Caceria de Reliquias: {0}/{1} enemigos." },
                { "event.daily_completed", "Evento diario completado: recibiste una recompensa rara." },
                { "event.daily_reward", "+100 EXP, +120 oro y desbloqueaste Alas de brasa" },
                { "event.daily_summary", "Caceria diaria {0}/{1}" },
                { "event.daily_done_summary", "Caceria diaria completada {0}/{1}" },
                { "event.weekly_started", "Evento semanal activo: Conquista del Valle." },
                { "event.weekly_progress", "Conquista semanal: {0}/{1} derrotas | elites {2}/{3}." },
                { "event.weekly_completed", "Evento semanal completado: Conquista del Valle." },
                { "event.weekly_reward", "+600 EXP, +500 oro, 2 Runas y 1 Manual de habilidades" },
                { "event.weekly_summary", "Conquista semanal {0}/{1} | elites {2}/{3}" },
                { "event.weekly_done_summary", "Conquista semanal completada {0}/{1} | elites {2}/{3}" },
                { "event.calendar_started", "Calendario activo: cada dia hay una actividad y un horario de jefe mundial." },
                { "event.calendar_weekly", "Actividad de hoy: Conquista semanal (revisa el progreso semanal)." },
                { "event.calendar_activity", "Actividad de hoy: {0} {1}/{2}" },
                { "event.calendar_progress", "{0}: {1}/{2}." },
                { "event.calendar_completed", "Actividad completada: {0}." },
                { "event.calendar_reward", "+250 EXP, +220 oro y 3 minerales opacos." },
                { "event.calendar_boss", "Jefe mundial: hoy a las {0:00}:{1:00} UTC (ventana 60 min)." },
                { "event.calendar_boss_waiting", "Jefe mundial: espera la ventana de hoy a las {0:00}:{1:00} UTC." },
                { "event.calendar_boss_done", "Jefe mundial de hoy completado." },
                { "event.calendar_boss_completed", "Jefe mundial derrotado dentro de la ventana diaria." },
                { "event.calendar_boss_reward", "+500 EXP, +300 oro y 1 runa de proteccion." },
                { "event.calendar_name_elite_surge", "Oleada de elites" },
                { "event.calendar_name_forge_festival", "Festival de la forja" },
                { "event.calendar_name_relic_rush", "Carrera de reliquias" },
                { "event.calendar_name_gold_rush", "Asalto del tesoro" },
                { "event.calendar_name_guild_war", "Guerra de clanes" },
                { "event.calendar_name_free_for_all", "Todos contra todos" },
                { "event.calendar_name_weekly_valley_conquest", "Conquista del Valle" },
                { "event.guild_unassigned", "Guerra de clanes: crea o unete a un clan desde el servidor." },
                { "event.guild_summary", "Clan {0}: contribucion {1}/{2} esta semana." },
                { "event.guild_done", "Clan {0}: evento semanal completado." },
                { "event.guild_completed", "Tu clan completo la contribucion semanal." },
                { "event.guild_reward", "Contribucion registrada; la recompensa final la valida el servidor." },
                { "event.ffa_ready", "Todos contra todos: disponible al conectar con un servidor autoritativo." },
                { "event.ffa_summary", "Todos contra todos: bajas {0} | derrotas {1} | puntuacion {2}." },
                { "season.started", "{0} activa: quedan {1} dias." },
                { "season.name", "Temporada {0}: Renacer del Valle" },
                { "season.summary", "{0} | Nivel {1}/{2} | XP {3}/{4} | quedan {5} dias" },
                { "season.level_up", "Subiste el pase de temporada {0} al nivel {1}." },
                { "season.reward", "Recompensa de temporada nivel {0}: {1}x {2} y {3} oro." },
                { "season.final_reward", "Recompensa final: Atuendo del eclipse desbloqueado." },

                // Atuendos y tienda de objetos
                { "cosmetic.none", "Atuendo predeterminado" },
                { "cosmetic.wings_none", "Sin alas" },
                { "cosmetic.unlocked", "Desbloqueaste {0}." },
                { "cosmetic.feed_unlocked", "Cosmetico desbloqueado: {0}" },
                { "cosmetic.bought", "Compraste {0}." },
                { "cosmetic.feed_bought", "Tienda: {0} por {1} oro" },
                { "cosmetic.shop_empty", "La tienda no tiene nuevos articulos para ti." },
                { "cosmetic.need_level", "Necesitas nivel {0} para comprar {1}." },
                { "cosmetic.need_gold", "Necesitas {0} oro para esa compra." },
                { "cosmetic.equipped", "Equipaste {0}." },
                { "cosmetic.unequipped", "Quitaste el {0}." },
                { "cosmetic.summary", "Atuendo: {0} | Alas: {1} | Coleccion {2}/{3}" },

                // HUD
                { "ui.game_title", "Valle de las Reliquias" },
                { "ui.version_subtitle", "Prototipo Android 0.1" },
                { "ui.attack", "ATK" },
                { "ui.potion", "POTION" },
                { "ui.buy_potion", "BUY 25" },
                { "ui.weapon", "WEAPON" },
                { "ui.armor", "ARMOR" },
                { "ui.equip", "EQUIPAR" },
                { "ui.talk", "HABLAR" },
                { "ui.pet", "MASCOTA" },
                { "ui.mount", "MONTURA" },
                { "ui.storage", "ALMACEN" },
                { "ui.stats", "STATS" },
                { "ui.telemetry", "DATOS" },
                { "ui.menu", "MENU" },
                { "ui.more", "MAS" },
                { "ui.explore", "EXPLORAR" },
                { "ui.item_shop", "TIENDA" },
                { "ui.outfit", "ATUENDO" },
                { "ui.wings", "ALAS" },
                { "ui.rebirth", "RENACER" },
                { "ui.menu_inventory", "Inventario" },
                { "ui.menu_equipment", "Equipo" },
                { "ui.menu_quest", "Mision" },
                { "ui.close", "CERRAR" },
                { "ui.online", "ONLINE" },
                { "ui.send", "SEND" },
                { "ui.chat_title", "Chat online local." },
                { "ui.stats_title", "Atributos" },
                { "ui.telemetry_title", "Telemetria de combate" },
                { "ui.telemetry_refresh", "ACTUALIZAR" },
                { "ui.telemetry_save", "GUARDAR" },
                { "ui.mobile_test", "TEST" },
                { "ui.skills", "HABILIDADES" },
                { "ui.graphics", "GRAFICOS" },
                { "ui.quality", "CALIDAD" },
                { "ui.performance", "RENDIMIENTO" },
                { "ui.profile", "Perfil actual: {0}" },
                { "ui.skills_summary", "PROGRESION DE HABILIDADES" },
                { "ui.skills_material_hint", "Manual de habilidades: mejora cada ranura con materiales." },
                { "ui.skill_level", "Nv{0}/{1}" },
                { "ui.skill_unlock", "DESBLOQUEA Nv{0}" },
                { "ui.skill_row", "{0}  {1}  Energia {2}" },
                { "ui.chat_collapse", "CHAT" },
                { "ui.chat_expand", "ABRIR CHAT" },
                { "ui.mobile_test_title", "Prueba movil" },
                { "ui.mobile_music", "MUSICA" },
                { "ui.mobile_sfx_down", "SFX -" },
                { "ui.mobile_sfx_up", "SFX +" },
                { "ui.mobile_music_down", "MUS -" },
                { "ui.mobile_music_up", "MUS +" },
                { "ui.mobile_export", "EXPORTAR QA" },
                { "mobile.audio", "Musica {0} | SFX {1} | Volumen musica {2}" },
                { "mobile.unavailable", "Diagnostico no disponible" },
                { "mobile.device", "Dispositivo {0} | DPI {1:0.#} | objetivo {2} FPS" },
                { "mobile.performance", "Sesion {0:0.#}s | FPS actual {1:0.#} promedio {2:0.#} minimo {3:0.#} | memoria {4:0.#} MB | enemigos {5} | POI {6}" },
                { "mobile.report_exported", "Reporte guardado en {0}" },
                { "telemetry.summary", "Kills {0} | Muertes {1} | Dano dado {2} | Dano recibido {3}" },
                { "telemetry.targets", "Objetivo TTK: normal {0:0.#}-{1:0.#}s | elite {2:0.#}-{3:0.#}s | jefe {4:0.#}-{5:0.#}s" },
                { "telemetry.zone_no_data", "{0} ({1}-{2}) | sin datos de combate" },
                { "telemetry.zone_line", "{0} ({1}-{2}) | muertes {3} | N {4} | E {5} | J {6}" },
                { "telemetry.no_kills", "sin kills" },
                { "telemetry.tier", "{0} kills, {1:0.0}s, {2}" },
                { "telemetry.fast", "RAPIDO" },
                { "telemetry.slow", "LENTO" },
                { "telemetry.ok", "OK" },
                { "telemetry.path", "Archivo local: {0}" },
                { "menu.inventory_count", "Objetos: {0}" },
                { "menu.item_line", "- {0} x{1}" },
                { "menu.equipment_stats", "Bonos: +{0} dano | +{1} vida | +{2:0.00} velocidad" },
                { "menu.slot_line", "{0}: {1}{2}" },
                { "menu.empty_slot", "Vacio" },
                { "menu.empty", "Sin datos" },
                { "menu.quest_title", "Mision: {0}" },
                { "menu.quest_objective", "- {0}: {1}/{2}" },
                { "menu.quest_reward", "Recompensa: {0} EXP | {1} oro" },
                { "slot.weapon", "Arma" },
                { "slot.helmet", "Casco" },
                { "slot.chest", "Pechera" },
                { "slot.gloves", "Guantes" },
                { "slot.pants", "Pantalones" },
                { "slot.boots", "Botas" },
                { "slot.cape", "Capa" },
                { "slot.necklace", "Collar" },
                { "slot.ring_left", "Anillo izquierdo" },
                { "slot.ring_right", "Anillo derecho" },
                { "slot.bracelet", "Brazalete" },
                { "slot.belt", "Cinturon" },
                { "slot.talisman", "Talisman" },
                { "hud.initial_status", "Fase 5: prototipo Android preparado para pruebas." },
                { "hud.controls_help", "WASD/joystick moverse  |  ATK/Space ataque  |  Q/E/R/F habilidades  |  G final  |  Click derecho camara" },
                { "hud.touch_help", "Joystick mover  |  Arrastra el mundo: camara  |  ATK atacar  |  Q/E/R/F habilidades  |  G final" },
                { "ui.minimap", "MINIMAPA" },
                { "regen.started", "Regenerando salud..." },
                { "hud.hint", "Cambia clase, completa la mision, mejora equipo y busca el monolito." },
                { "hud.player_hp", "Jugador {0}/{1}" },
                { "hud.target_hp", "Objetivo {0}/{1}" },
                { "hud.no_target", "Sin objetivo" },
                { "hud.progression", "Nivel {0}  {1}  Oro {2}{3}{4}" },
                { "hud.exp", "EXP {0}/{1}" },
                { "hud.exp_max", "EXP MAX" },
                { "hud.level_short", "Nv {0}" },
                { "hud.level_max", "Nv {0} MAX" },
                { "hud.points_suffix", "  Puntos {0}" },
                { "hud.exp_bonus_suffix", "  (+{0}% EXP)" },

                // Identidad / creacion de personaje
                { "identity.default_name", "Heroe" },
                { "identity.gender_male", "Masculino" },
                { "identity.gender_female", "Femenino" },
                { "identity.display", "{0} ({1})" },
                { "identity.name_label", "{0}\n{1} - {2}" },
                { "character.title", "Crear personaje" },
                { "character.subtitle", "Elige clase, sexo y nombre para entrar al Valle de las Reliquias." },
                { "character.select_title", "Seleccionar personaje" },
                { "character.select_subtitle", "Tu personaje local esta listo para volver al valle." },
                { "character.saved_label", "PERSONAJE GUARDADO" },
                { "character.local_save_note", "Progreso local disponible en este dispositivo." },
                { "character.ready_title", "Listo para entrar" },
                { "character.ready_subtitle", "Continua tu aventura o prepara un personaje nuevo para esta prueba." },
                { "character.level_details", "Nivel {0}  |  EXP {1}  |  Oro {2}" },
                { "character.new_title", "Crear nuevo personaje" },
                { "character.new_subtitle", "Personaliza tu aventurero antes de entrar al Valle de las Reliquias." },
                { "character.name_label", "Nombre del personaje" },
                { "character.name_placeholder", "nombre del personaje" },
                { "character.class_label", "Clase" },
                { "character.gender_label", "Sexo" },
                { "character.create_button", "CREAR" },
                { "character.continue_button", "CONTINUAR" },
                { "character.enter_button", "ENTRAR AL VALLE" },
                { "character.new_button", "CREAR NUEVO PERSONAJE" },
                { "character.back_button", "VOLVER" },
                { "server.title", "Servidor" },
                { "server.active_profile", "S-01 activo para esta prueba" },
                { "server.coming_soon", "Nuevos mundos estaran disponibles proximamente." },
                { "server.address_label", "Direccion de prueba" },
                { "server.connection_status", "Estado de conexion" },
                { "character.created", "Personaje creado: {0}" },
                { "character.created_feed", "Entraste como {0}" },
                { "character.welcome_back", "Bienvenido de nuevo: {0}" },
                { "character.loaded_feed", "Partida cargada: nivel {0}" },
                { "character.preview", "{0}  |  {1}  |  {2}" },
                { "class.guerrero", "Guerrero" },
                { "class.ninja", "Ninja" },
                { "class.chaman", "Chaman" },
                { "class.umbra", "Umbra" }
            };
        }
    }
}
